content/en/docs/usage/sequencer/effects/pixel/bars/Bars_basic.md, content/en/docs/usage/sequencer/effects/pixel/bars/_index.md
=> Bars Effect Help Content

content/en/docs/usage/sequencer/effects/pixel/butterfly/Butterfly_basic.md, content/en/docs/usage/sequencer/effects/pixel/butterfly/_index.md
=> Butterfly Effect Help

content/en/docs/usage/sequencer/effects/pixel/morph/_index.md, content/en/docs/usage/sequencer/effects/pixel/morph/morph_basic.md, content/en/docs/usage/sequencer/effects/pixel/morph/morph_freeform.md, content/en/docs/usage/sequencer/effects/pixel/morph/morph_pattern.md, content/en/docs/usage/sequencer/effects/pixel/morph/morph_time_based.md
=> Morph Effect Help

.github/workflows/docker-production.yml, .github/workflows/docker-staging.yml, .github/workflows/docker.yml
Updates docker.yml to be a generic, reusable workflow with inputs to specify the hugo environment to build and the name of the container image to create.
Adds new workflows for the production and staging environments which delegate to the reusable docker.yml workflow with inputs appropriate for each environment.
=> Update docker workflow to support multiple environments

config.toml, config.yaml, config/_default/config.toml, config/production/config.toml, config/staging/config.toml, config/staging/params.toml, content/en/docs/_index.md, content/en/docs/concepts/_index.md, content/en/docs/started/_index.md, content/en/docs/tutorials/_index.md, content/en/docs/usage/_index.md, layouts/robots.txt
Add environment specific settings.
=> Core configuration updates

content/en/docs/usage/general/import-export/_index.md, content/en/docs/usage/general/import-export/falcon-export.md, content/en/docs/usage/general/import-export/sequence-export.md, content/en/docs/usage/general/import-export/sequence-import.md
* Split the sequence import and export into two pages and organize under a header section.
* Add content for the Falcon Pi Player Export.
=> Create Import / Export sections

config/_default/config.toml, config/production/services.toml, layouts/partials/feedback.html, layouts/partials/page-meta-links.html
Configure Google Analytics and update the feedback template to work with the GA4.
Update the page meta template to support our JIRA link for Create project issue.
=> Site config updates

content/en/docs/usage/sequencer/effects/pixel/vertical-meter/_index.md
=> Vertical Meter Help

content/en/docs/usage/sequencer/effects/pixel/text/_index.md, content/en/docs/usage/sequencer/effects/pixel/tree/_index.md, content/en/docs/usage/sequencer/effects/pixel/vertical-meter/_index.md
=> Incorrect Alias

content/en/docs/usage/sequencer/effects/pixel/video/_index.md
=> Video Effect Help

content/en/docs/usage/sequencer/effects/pixel/video/_index.md, content/en/docs/usage/sequencer/effects/pixel/vu-meter/_index.md
=> VU Meter Effect Help

content/en/docs/usage/sequencer/effects/pixel/vertical-meter/_index.md, content/en/docs/usage/sequencer/effects/pixel/video/_index.md, content/en/docs/usage/sequencer/effects/pixel/vu-meter/_index.md
Vertical Meter Typos and Corrections
=> Vertical Meter Typos and Corrections

content/en/docs/usage/sequencer/effects/pixel/wave/_index.md
=> Wave Effect Help

content/en/docs/usage/sequencer/effects/intelligent-fixture/set-zoom/_index.md
=> Set Zoom Effect Help

content/en/docs/usage/sequencer/effects/intelligent-fixture/gobo/_index.md
=> Gobo Effect Help

content/en/docs/usage/sequencer/effects/intelligent-fixture/gobo/_index.md, content/en/docs/usage/sequencer/effects/intelligent-fixture/prism/_index.md, content/en/docs/usage/sequencer/effects/intelligent-fixture/spin-color-wheel/_index.md
=> Prism Effect Help

content/en/docs/usage/sequencer/effects/intelligent-fixture/fixture/_index.md, content/en/docs/usage/sequencer/effects/intelligent-fixture/gobo/_index.md, content/en/docs/usage/sequencer/effects/intelligent-fixture/prism/_index.md, content/en/docs/usage/sequencer/effects/intelligent-fixture/spin-color-wheel/_index.md
=> Fixture Effect Help

content/en/docs/usage/sequencer/effects/intelligent-fixture/fixture/_index.md, content/en/docs/usage/sequencer/effects/intelligent-fixture/frost/_index.md, content/en/docs/usage/sequencer/effects/intelligent-fixture/gobo/_index.md, content/en/docs/usage/sequencer/effects/intelligent-fixture/prism/_index.md, content/en/docs/usage/sequencer/effects/intelligent-fixture/spin-color-wheel/_index.md
=> Frost Effect Help

content/en/docs/usage/sequencer/effects/intelligent-fixture/fixture-strobe/_index.md, content/en/docs/usage/sequencer/effects/intelligent-fixture/fixture/_index.md, content/en/docs/usage/sequencer/effects/intelligent-fixture/frost/_index.md, content/en/docs/usage/sequencer/effects/intelligent-fixture/gobo/_index.md, content/en/docs/usage/sequencer/effects/intelligent-fixture/prism/_index.md, content/en/docs/usage/sequencer/effects/intelligent-fixture/spin-color-wheel/_index.md
=> Fixture Strobe Effect Help

config/_default/config.toml
* Change the forum icons to fa-user-group.
* Change the copyright tag to remove the duplicate date.
* Disable the about link in the footer since it is in the header.
=> Improve footer appearance

content/en/download/develop-build.md, content/en/download/legacy-build.md, content/en/download/logos.md, content/en/download/release-build.md
* Add Overview sections to the pages.
* Add links to the install page and developer sections for contributing back.
* Refine the Legacy 2.x page with some more information.
=> Apply feedback updates to the Downloads section

content/en/docs/usage/programming-api/comand-line-api.md, content/en/docs/usage/programming-api/web-api.md
* Update the front matter to have a description.
* Add Overview section to both pages.
=> Update to follow layout patterns

content/en/docs/tutorials/preview-videos.md, content/en/docs/usage/preview/_index.md, content/en/docs/usage/preview/custom-prop-editor.md, content/en/docs/usage/preview/preview-adding-items.md, content/en/docs/usage/preview/preview-basic-shapes.md, content/en/docs/usage/preview/preview-common-settings.md, content/en/docs/usage/preview/preview-linking-elements.md, content/en/docs/usage/preview/preview-main-screen.md, content/en/docs/usage/preview/preview-setup.md, content/en/docs/usage/preview/smart-objects/_index.md, content/en/docs/usage/preview/smart-objects/intelligent-fixture.md, content/en/docs/usage/preview/smart-objects/preview-arch.md, content/en/docs/usage/preview/smart-objects/preview-candy-cane.md, content/en/docs/usage/preview/smart-objects/preview-icicles.md, content/en/docs/usage/preview/smart-objects/preview-mega-tree.md, content/en/docs/usage/preview/smart-objects/preview-net.md, content/en/docs/usage/preview/smart-objects/preview-star.md
* Update front matter with descriptions and proper authors.
* Remove some duplicate content from the Basic Drawing that was covered in the Common Settings section.
* Ensure consistency of an Overview section on each page.
=> Apply standard patterns to the preview sections

content/en/docs/usage/sequencer/sequencer-basics/draw-mode.md, content/en/docs/usage/sequencer/sequencer-basics/effect-editor/_index.md, content/en/docs/usage/sequencer/sequencer-basics/effect-editor/inline-curve-editor.md, content/en/docs/usage/sequencer/sequencer-basics/effect-editor/inline-gradient-editor.md
* Fix the front matter to have proper author and description.
* Add Overview sections.
* Tweak the content a bit for clarity.
=> Move the Effect Editor under the Sequencer

content/en/docs/usage/sequencer/effects/_index.md, content/en/docs/usage/sequencer/effects/device-action/_index.md
=> Device Action Effects

content/en/docs/usage/sequencer/effects/device-action/custom-value/_index.md
=> Custom Value Effect Help

content/en/docs/usage/sequencer/effects/device-action/custom-value/_index.md
=> VixenCore Review Comments

content/en/docs/usage/sequencer/effects/device-action/custom-value/_index.md, content/en/docs/usage/sequencer/effects/device-action/launcher/_index.md
=> Launcher Effect Help

content/en/docs/usage/sequencer/effects/basic/_index.md, content/en/docs/usage/sequencer/effects/device-action/_index.md, content/en/docs/usage/sequencer/effects/intelligent-fixture/_index.md, content/en/docs/usage/sequencer/effects/pixel/_index.md
=> Ordering Effect Types

content/en/_index.html
* Add a description for the main landing page for search engines.
* Correct the Facebok link in the main footer section.
* Change the visual description to match the description section.
=> Update main site metadata

.github/workflows/docker-production.yml, .github/workflows/docker-staging.yml, .github/workflows/docker.yml
Use GitHub Actions Environments to provide different secret values in each environment and restrict production deployments to the master branch.
=> Use GitHub Actions Environments

data/release/latest.json, layouts/shortcodes/blocks/feature-release.html, layouts/shortcodes/devbuild-first.html, layouts/shortcodes/release-all.html, layouts/shortcodes/release-latest.html
* Set dates to use local time.
* Set Actions timezone to be America/Chicago.
=> Localization of dates

content/en/docs/usage/sequencer/effects/pixel/weave/_index.md
Adding Weave video to help page.
=> Adding Weave video to help page.

content/en/docs/usage/display-setup/display-patching/dimming-curves.md
Adding an alias to fix broken link with older versions of Vixen.
=> Fix broken dimming curve help link.

content/en/docs/usage/display-setup/display-elements/intelligent-fixture-wizard/edit-functions.md
Updating edit-functions for VIX-3522
=> Updating edit-functions for VIX-3522

content/en/docs/usage/preview/smart-objects/intelligent-fixture.md
VIX-3519 Updating help documentation for min/max strobe rate and strobe duration
=> VIX-3519 Updating help documentation for min/max strobe rate and strobe duration

content/en/docs/usage/preview/smart-objects/intelligent-fixture.md
Updating the help for several new Intelligent Fixture properties. Property groups were added to the software so the help was updated to match that organization.
=> Update Intelligent Fixture Preview Help

content/en/docs/usage/sequencer/effects/device-action/custom-value/_index.md
This update is a result of trying to help a user on the red site.   Please confirm my note is technically accurate.
=> Adding a note to clarify how to use this effect with numerical values

content/en/docs/usage/sequencer/effects/device-action/custom-value/_index.md, content/en/docs/usage/sequencer/effects/pixel/border/_index.md, content/en/docs/usage/sequencer/effects/pixel/border/border_advanced.md, content/en/docs/usage/sequencer/effects/pixel/border/border_marquee.md, content/en/docs/usage/sequencer/effects/pixel/border/border_simple.md
VIX-3406 Updating online help for Border effect to include Marquee Mode
=> VIX-3406 Updating online help for Border effect to include Marquee Mode

content/en/docs/usage/sequencer/effects/pixel/whirlpool/_index.md
Adding link to Whirlpool Video
=> Adding link to Whirlpool Video

content/en/docs/usage/sequencer/effects/pixel/shockwave/_index.md
=> Diamond Shockwave Help

content/en/docs/usage/sequencer/effects/pixel/border/_index.md
Adding the video for the Border Effect to the online help.
=> VIX-3406 Border Effect Video

package-lock.json
* Several packages had audit updates. Braces had a specific vulnerability called out by the github dependabot.
=> Update package dependencies for vulnerabilities

content/en/docs/usage/sequencer/effects/intelligent-fixture/line-dance/_fan.md, content/en/docs/usage/sequencer/effects/intelligent-fixture/line-dance/_index.md
New Line Dance / Fan Effect Documentation
=> New Line Dance / Fan Effect Documentation

content/en/docs/usage/sequencer/effects/intelligent-fixture/line-dance/_fan.md
Adding Fan Video To Online Help
=> Adding Fan Video To Online Help

.github/workflows/docker.yml, config/_default/config.toml, content/en/_index.html, content/en/developer/contribute-vixen.md, go.mod, go.sum, layouts/partials/feedback.html
Both of these were significantly behind so it was a big move forward. I fixed the issues I found, but there may be others sine I did not scour every section of the docs. May need subsequent updates to correct leftover items. 
Hugo 136.5 and Docsy 11.
=> Hugo & Docsy upgrade

content/en/docs/usage/sequencer/effects/pixel/glediator/_index.md
* Added link to Jinx! website
* Added info on how to use Jinx! files in the Glediator effect.
=> Update gled docs with info about Jinx

content/en/docs/usage/sequencer/sequencer-basics/edit-functions.md, content/en/docs/usage/sequencer/sequencer-basics/timeline.md
Descriptions now explain
1) Only immmediate left or right effect will be adjoined
2) Shift+Alt will adjoin effects at same Layer
=> VIX 2615 Updated descriptions to match final design

content/en/docs/usage/sequencer/sequencer-basics/effect-editor/inline-curve-editor.md, content/en/docs/usage/sequencer/sequencer-basics/effect-editor/inline-gradient-editor.md
* Reorganize the content to make it easier to read.
* Add the shortcut info to reverse a curve.
=> Update the curve and gradient editor pages

content/en/docs/usage/sequencer/effects/basic/lipsync/_index.md
* Add a link to Terrys video on how to use the Autolyrics tracks in Vixen.
=> Add info about Autolyrics

content/en/developer/git-information.md
* Add proper headings for the Tools section items.
* Add more information into the Visual Studio section for Git.
=> Update additional Git details

content/en/developer/contribute-vixen.md, content/en/developer/git-information.md, content/en/developer/visual-studio.md
Additional updates to provide more information to potential developers.
=> Dev docs updates

content/en/developer/contribute-vixen.md, content/en/developer/visual-studio.md
* Add content on the project structure from the main source README.
* Update the dependencies to include the v143 version of C++ tools.
* Add info on the editorconfig setup for the code style to the Visual Studio page.
=> Update developer guidlines to most recent info
